apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb.primary.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
    app.kubernetes.io/component: primary
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.primary.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.primary.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.primary.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.primary.service.type }}
  {{- if and .Values.primary.service.clusterIP (eq .Values.primary.service.type "ClusterIP") }}
  clusterIP: {{ .Values.primary.service.clusterIP }}
  {{- end }}
  {{- if .Values.primary.service.sessionAffinity }}
  sessionAffinity: {{ .Values.primary.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.primary.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.primary.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- if or (eq .Values.primary.service.type "LoadBalancer") (eq .Values.primary.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.primary.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.primary.service.type "LoadBalancer") (not (empty .Values.primary.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.primary.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .Values.primary.service.type "LoadBalancer") (not (empty .Values.primary.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.primary.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: mysql
      port: {{ .Values.primary.service.ports.mysql }}
      protocol: TCP
      targetPort: mysql
      {{- if and (or (eq .Values.primary.service.type "NodePort") (eq .Values.primary.service.type "LoadBalancer")) (not (empty .Values.primary.service.nodePorts.mysql)) }}
      nodePort: {{ .Values.primary.service.nodePorts.mysql }}
      {{- else if eq .Values.primary.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.primary.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.primary.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  selector:
    {{- include "mariadb.primary.selectorLabels" . | nindent 4 }}
---
{{- if eq .Values.architecture "replication" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb.secondary.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
    app.kubernetes.io/component: secondary
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.secondary.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.secondary.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.secondary.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.secondary.service.type }}
  {{- if and .Values.secondary.service.clusterIP (eq .Values.secondary.service.type "ClusterIP") }}
  clusterIP: {{ .Values.secondary.service.clusterIP }}
  {{- end }}
  {{- if .Values.secondary.service.sessionAffinity }}
  sessionAffinity: {{ .Values.secondary.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.secondary.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.secondary.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- if or (eq .Values.secondary.service.type "LoadBalancer") (eq .Values.secondary.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.secondary.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.secondary.service.type "LoadBalancer") (not (empty .Values.secondary.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.secondary.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .Values.secondary.service.type "LoadBalancer") (not (empty .Values.secondary.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.secondary.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: mysql
      port: {{ .Values.secondary.service.ports.mysql }}
      protocol: TCP
      targetPort: mysql
      {{- if and (or (eq .Values.secondary.service.type "NodePort") (eq .Values.secondary.service.type "LoadBalancer")) (not (empty .Values.secondary.service.nodePorts.mysql)) }}
      nodePort: {{ .Values.secondary.service.nodePorts.mysql }}
      {{- else if eq .Values.secondary.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.secondary.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.secondary.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  selector:
    {{- include "mariadb.secondary.selectorLabels" . | nindent 4 }}
{{- end }}
