{{- if .Values.ingress.enabled }}
{{- $fullName := include "keycloak.fullname" . -}}
{{- $servicePort := .Values.ingress.servicePort -}}
{{- $path := include "keycloak.tplvalues.render" (dict "value" .Values.ingress.path "context" .) -}}
apiVersion: {{ if .Values.ingress.apiVersion }}{{ .Values.ingress.apiVersion }}{{ else }}networking.k8s.io/v1{{ end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ include "keycloak.namespace" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- if and .Values.ingress.tls (eq .Values.ingress.controller "gce") }}
    ingress.gcp.kubernetes.io/pre-shared-cert: {{ printf "%s-tls" (tpl .Values.ingress.hostname .) }}
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ include "keycloak.tplvalues.render" (dict "value" $value "context" $) | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ include "keycloak.tplvalues.render" (dict "value" .Values.ingress.ingressClassName "context" .) }}
  {{- end }}
  rules:
    - host: {{ tpl .Values.ingress.hostname . | quote }}
      http:
        paths:
          {{- if .Values.ingress.extraPaths }}
          {{- toYaml .Values.ingress.extraPaths | nindent 10 }}
          {{- end }}
          - path: {{ $path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: {{ $servicePort }}
    {{- range .Values.ingress.extraHosts }}
    - host: {{ .name | quote }}
      http:
        paths:
          - path: {{ default $path .path }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: {{ $servicePort }}
    {{- end }}
    {{- if .Values.ingress.extraRules }}
    {{- include "keycloak.tplvalues.render" (dict "value" .Values.ingress.extraRules "context" $) | nindent 4 }}
    {{- end }}
  {{- if or .Values.ingress.tls .Values.ingress.extraTls }}
  tls:
    {{- if .Values.ingress.tls }}
    - hosts:
        - {{ tpl .Values.ingress.hostname . | quote }}
      {{- if .Values.ingress.selfSigned }}
      secretName: {{ printf "%s-tls" (tpl .Values.ingress.hostname .) }}
      {{- else }}
      secretName: {{ printf "%s-tls" (tpl .Values.ingress.hostname .) }}
      {{- end }}
    {{- end }}
    {{- if .Values.ingress.extraTls }}
    {{- include "keycloak.tplvalues.render" (dict "value" .Values.ingress.extraTls "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
---
{{- if and .Values.ingress.enabled .Values.ingress.selfSigned }}
{{- $ca := genCA "keycloak-ca" 365 }}
{{- $cert := genSignedCert .Values.ingress.hostname nil (list .Values.ingress.hostname) 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-tls" (tpl .Values.ingress.hostname .) }}
  namespace: {{ include "keycloak.namespace" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
  ca.crt: {{ $ca.Cert | b64enc }}
{{- end }}
