{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ default (include "keycloak.namespace" .) .Values.metrics.prometheusRule.namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    {{- with .Values.metrics.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- with .Values.metrics.prometheusRule.groups }}
  groups:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
